// *** Enums ***

Enum UserFlow {
  DISTRIBUTION
  MANUFACTURING
  CSLOG_PLATFORM
  GROUP_PLATFORM
  OFFICE
  MA
  OTHER
}

Enum Scope {
  MARKETS
  REGIONS
  MAISONS
  GROUP
}

Enum Responsibility {
  REQUESTER
  REVIEWER
  APPROVER
}

Enum BudgetProject {
  YES
  NO
  PARTIALLY
}

Enum Status {
  IN_PROGRESS
  SUBMITTED
  PRENDING_REVIEW
  FAVORABLE
  FAVORABLE_WITH_CONDITIONS
  CHANGES_REQUESTED
  UNFAVORABLE
  APPROVED
  APPROVED_WITH_CONDITIONS
  REJECTED
  CANCELED
  ROLE_CHANGED
}

Enum RoleCode {
  INPUT_CAR_ENT
  INPUT_CAR_BRD
  INPUT_CAR_CDG
}

// *** Master data tables ***
// Those value can be updated super user only

Table MD_CarStream {
  Id varchar(2) [not null, note: "Ex : 7"]
  Name varchar(60) [not null, note: "Ex : Distribution - INTERNAL BOUTIQUE"]
}

Table MD_CarType {
  Code varchar(3) [not null, note: "Ex : NEW"]
  Text varchar(60) [not null, note: "Ex : Opening Perm."]
}

Table MD_BoutiqueEnvironment {
  Code varchar(4) [not null, note: "Ex : RI02"]
  Text varchar(60) [not null, note: "Ex : Interior Boutique"] 
}

Table MD_BoutiqueType {
  Code varchar(4) [not null, note: "Ex : RI02"]
  Text varchar(60) [not null, note: "Ex : Interior Boutique"] 
}

// Can be updated by Excel upload
Table MD_Entity {
  Code varchar(4) [not null, note: "Ex : Z108"]
  LocalCurrrency varchar(5) [not null, note: "Ex : EUR"]
  Name varchar(60) [not null, note: "Ex : Richemont France"]
  Region varchar [not null, ref: > MD_Market.Region]
  Market varchar [not null, ref: > MD_Market.Country] // country
}

Table MD_RoleMatrix {
  Scope Scope [not null]
  Responsibility Responsibility [not null]
  UserFlow UserFlow [not null, note : "Ex : DISTRIBUTION"]
  Order int [not null, note : "Defines the order of approval in a given scope and responsibility"]
  Role varchar(200) [not null, note : "Ex : Chairman" ]
}

Table StreamMatrix {
  UserFlow UserFlow [not null, note : "Ex : DISTRIBUTION"]
  CarStream varchar(2) [not null, ref: > MD_CarStream.Id]
  CarType varchar(3) [not null, ref: > MD_CarType.Code]
}

//to match the correct screen
Table MD_StreamScreen {
  CarStream varchar(2) [not null, ref: > MD_CarStream.Id]
  CarType varchar(3) [not null, ref: > MD_CarType.Code]
  ScreenName varchar [note : "Screen number from 1 to 9"]
}

//maison + group 
Table MD_BusinessArea {
  Code varchar [not null, note: "Ex : CAR OR RCHMT, ..."]
  Name varchar [not null, note: "Ex : Cartier OR Richemont, ..."]
  Picture blob
}

Table MD_Region {
  Name varchar [not null, note: "Ex : Europe Middle East and Africa"]
}

Table MD_Market {
  Country varchar [PK, not null, note: "Ex : FRANCE"]
  Code varchar [not null, note: "Ex : FR"]
  Region varchar [not null, ref: > MD_Region.Name]
}

// This table will be sync from SAP SEM in the futur
Table MD_UserRoles {
  Email varchar [not null]
  SAPUserId varchar [not null]
  Role_Code RoleCode [not null]
  Maison varchar [not null]
  ReportingEntity varchar [not null]
  Name varchar [not null]
  Surname varchar [not null]
}

// *** App tables ***

// Mendix default user table contains firstname/lastname/email etc
// Specialisation table for user
Table User {
  Id varchar [pk, not null]
  JobTitle varchar
  BusinessArea varchar [ref: > MD_BusinessArea.Code]
  Region varchar [ref: > MD_Region.Name]
  Market varchar [ref: > MD_Market.Country]
  picture blob
}

Table RequestRole {
  Id varchar [pk]
  UserId varchar [ref: > User.Id]
  RequestId varchar [ref: > Request.SEMNumber]
  Scope Scope
  Responsibility Responsibility
  Role varchar(200) [not null, note : "Ex : Chairman" ]
  IsPendingAction boolean
  CreatedOn datetime
  CreatedBy varchar [ref: > User.Id]
  UpdatedOn datetime
  UpdatedBy varchar [ref: > User.Id]
}

Table Request {
  Requester varchar [ref: > User.Id, not null]
  SEMNumber varchar [pk] 
  CarStream varchar(2) [not null, ref: > MD_CarStream.Id]
  CarType varchar(3) [not null, ref: > MD_CarType.Code]
  Currency varchar [ not null]
  Status Status [not null]
  CreatedOn datetime [not null]
  CreatedBy varchar [ref: > User.Id, not null]
  UpdatedOn datetime
  UpdatedBy varchar [ref: > User.Id]
}

Table RequestVersion {
  Id varchar [pk]
  SEMNumber varchar [ref: > Request.SEMNumber]
  Scope Scope [not null]
  CreatedOn datetime
  CreatedBy varchar [ref: > User.Id]
  UpdatedOn datetime
  UpdatedBy varchar [ref: > User.Id]
}

Table Attachments {
  Id varchar [pk]
  FileName varchar
  Binary blob
  RequestVersionId varchar [ref: > RequestVersion.Id]
  CreatedOn datetime
  CreatedBy varchar
  UpdatedOn datetime
  UpdatedBy varchar
}

Table RequestInformation {
  Id varchar [pk]
  RequestVersionId varchar [ref: - RequestVersion.Id]
  FxRate decimal [not null]
  Maison varchar [not null, ref: > MD_BusinessArea.Code]
  ReportingEntity varchar [not null, note: "Ex : 59 - Richmt Korea", ref: > MD_Entity.Code]
  Stream varchar [note: "Ex : Manufacturing"]
  RequestType varchar [note: "Ex : Relocation without lease renewal"]
  RequestName varchar [note: "Ex : Hyundai main"]
  StreetName varchar [note: "Ex : 123 Main St"]
  BoutiqueType varchar(4) [note: "Ex : Flagship", ref: > MD_BoutiqueType.Code]
  BoutiqueEnvironment varchar(4) [note: "Ex : Street Boutique", ref: > MD_BoutiqueEnvironment.Code]
  Location varchar [note: "Ex : Seoul"] // City 
  Country varchar [note: "Ex : France", ref: > MD_Market.Country] // REGION-> MARKET-> COUNTRY
  CompletionDate datetime [note: "Format: dd.mm.yyyy"]
  BudgetProject BudgetProject [not null]
  BudgetProjectDetails text []
  TranferToAnotherMaison boolean //only for screen 4
  TranferToAnotherMaisonDetails text [] //only for screen 4
  PartnersName varchar(10000) [note: "Ex : ABC Real Estate"] //only for screen 5
  ContractDuration varchar(10000) [note: "Ex : 10 years"] //only for screen 5
  ReviewByLegal boolean //only for screen 8
  ReviewByProcurement boolean //only for screen 8
}

// for screen 1, 2 and 3, 5
Table FinancialCommitmentComposition {
  Id varchar [pk]
  RequestVersionId varchar [ref: - RequestVersion.Id]
  TotalCapex decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 5, 6, 7, 8, 9
  LandLordContribution decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 5
  MaisonCapex decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 5
  KeyMoney decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 3
  LeaseDeposit decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 3, 6, 9
  InternationalisationCost decimal [note: "Ex : 2536.99"] // only for screen 1, 2
  Inventories decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 5
  FixedLeaseCommitment decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 3, 6, 9
  TemporaryBoutique decimal [note: "Ex : 2536.99"] // only for screen 1, 2
  OtherCommitments decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 5, 7, 8, 9
  TotalInvestedCapital decimal [note: "Ex : 2536.99"] // only for screen 1, 2, 3, 5
  OneOffCosts decimal [note: "Ex : 2536.99"] // only for screen 6, 7
  OpexCommitments decimal [note: "Ex : 2536.99"] // only for screen 6, 8, 9
  TotalFinancialCommitment decimal [note: "Ex : 2536.99"] // only for screen 6, 7, 9
}

Table Activity {
  Id varchar [pk]
  Type varchar
  Status Status
  HasConditions boolean
  Conditions text
  Comments text
  RequestId varchar [ref: > Request.SEMNumber]
  CreatedDate datetime
  CreatedBy varchar [ref: > User.Id]
  CreatedByRole RoleCode
}